### PR TITLE
Updated append-transform dependency.

### LINKED ISSUE #7: Update `append-transform`
See https://github.com/TypeStrong/ts-node/issues/183#issuecomment-241302682. I recently updated `ts-node` to follow the same require extension transform pattern as `pirates` and the hook I had added originally to `instabul`. The problem now is that falling back to the "next loader", which in this case is `istanbul`, results in the old version of `append-transform` that threw errors instead of loading via `.js`.

### PR DESCRIPTION
**Pull request by artdude543**
Fixes #7

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by donande** [comment]
Hi all,

are there news on this merge request? It's been a while.
Lifting dependency `append-transform` to `0.4.0` solves a very problematic issue in relation to typescript and the mocha testing framework. Please see also TypeStrong/ts-node#183.

Greetings and thank you in advance.

**Comment by bcoe** [comment]
@artdude543 @donande sorry about this pull request falling off my radar! let's get this merged ASAP.

**Comment by bcoe** [comment]
@artdude543 @donande this fix is now available in the `next` version of `nyc`, which I would love help testing:

`npm i nyc@next`

And has been published to npm.

**Pull request merged**
